const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  // admin
  FETCH_GENDER: "FETCH_GENDER",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  FETCH_POSITION: "FETCH_POSITION",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  FETCH_ROLE: "FETCH_ROLE",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  SAVE_USER: "SAVE_USER",
  SAVE_USER_FAILD: "SAVE_USER_FAILD",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_FAILD: "DELETE_USER_FAILD",

  FETCH_USERS: "FETCH_USERS",
  FETCH_USERS_FAIL: "FETCH_USERS_FAIL",

  FETCH_EDIT_USERS: "FETCH_EDIT_USERS",
  FETCH_EDIT_USERS_FAIL: "FETCH_EDIT_USERS_FAIL",

  FETCH_DOCTOR: "FETCH_DOCTOR",
  FETCH_DOCTOR_FAIL: "FETCH_DOCTOR_FAIL",
});

export default actionTypes;
