const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",


  // AUTH PATIENT
  PATIENT_LOGIN_SUCCESS: "PATIENT_LOGIN_SUCCESS",
  PATIENT_LOGIN_FAIL: "PATIENT_LOGIN_FAIL",
  PATIENT_LOGOUT: "PATIENT_LOGOUT",

  // AUTH DOCTOR
  DOCTOR_LOGIN_SUCCESS: "DOCTOR_LOGIN_SUCCESS",
  DOCTOR_LOGIN_FAIL: "DOCTOR_LOGIN_FAIL",
  DOCTOR_LOGOUT: "DOCTOR_LOGOUT",

  // AUTH ADMIN
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",

  //======================================================
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  //======================================================

  // admin

  FETCH_GENDER: "FETCH_GENDER",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  FETCH_POSITION: "FETCH_POSITION",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  FETCH_ROLE: "FETCH_ROLE",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  SAVE_USER: "SAVE_USER",
  SAVE_USER_FAILD: "SAVE_USER_FAILD",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_FAILD: "DELETE_USER_FAILD",

  FETCH_USERS: "FETCH_USERS",
  FETCH_USERS_FAIL: "FETCH_USERS_FAIL",

  FETCH_EDIT_USERS: "FETCH_EDIT_USERS",
  FETCH_EDIT_USERS_FAIL: "FETCH_EDIT_USERS_FAIL",

  FETCH_DOCTOR: "FETCH_DOCTOR",
  FETCH_DOCTOR_FAIL: "FETCH_DOCTOR_FAIL",

  FETCH_ALL_DOCTOR: "FETCH_ALL_DOCTOR",
  FETCH_ALL_DOCTOR_FAIL: "FETCH_ALL_DOCTOR_FAIL",

  SAVE_DETAIL_DOCTOR: "SAVE_DETAIL_DOCTOR",
  SAVE_DETAIL_DOCTOR_FAIL: "SAVE_DETAIL_DOCTOR_FAIL",

  GET_DETAIL_DOCTOR: "GET_DETAIL_DOCTOR",
  GET_DETAIL_DOCTOR_FAIL: "GET_DETAIL_DOCTOR_FAIL",

  FETCH_ALL_HOUR: "FETCH_ALL_HOUR",
  FETCH_ALL_HOUR_FAIL: "FETCH_ALL_HOUR_FAIL",

  FETCH_ALL_REQUIRED: "FETCH_ALL_REQUIRED",
  FETCH_ALL_REQUIRED_FAIL: "FETCH_ALL_REQUIRED_FAIL",

  FETCH_SAVE_PATIENT_BOOKING: "FETCH_SAVE_PATIENT_BOOKING",
  FETCH_SAVE_PATIENT_BOOKING_FAIL: "FETCH_SAVE_PATIENT_BOOKING_FAIL",

  // specialty
  FETCH_SAVE_SPECIALTY: "FETCH_SAVE_SPECIALTY",
  FETCH_SAVE_SPECIALTY_FAIL: "FETCH_SAVE_SPECIALTY_FAIL",

  FETCH_ALL_SPECIALTY: "FETCH_ALL_SPECIALTY",
  FETCH_ALL_SPECIALTY_FAIL: "FETCH_ALL_SPECIALTY_FAIL",

  // clinic
  FETCH_SAVE_CLINIC: "FETCH_SAVE_CLINIC",
  FETCH_SAVE_CLINIC_FAIL: "FETCH_SAVE_CLINIC_FAIL",

  FETCH_ALL_CLINIC: "FETCH_ALL_CLINIC",
  FETCH_ALL_CLINIC_FAIL: "FETCH_ALL_CLINIC_FAIL",


});




export default actionTypes;
